export const GET_SINGLE_BLOG = 'GET_SINGLE_BLOG';
export const GET_SINGLE_BLOG_SUCCESS = 'GET_SINGLE_BLOG_SUCCESS';
export const GET_SINGLE_BLOG_FAILURE = 'GET_SINGLE_BLOG_FAILURE';

export const GET_ALL_BLOG = 'GET_ALL_BLOG';
export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS';
export const GET_ALL_BLOG_FAILURE = 'GET_ALL_BLOG_FAILURE';

export const POST_BLOGS = "POST_BLOGS";
export const POST_BLOGS_SUCCESS = 'POST_BLOGS_SUCCESS';
export const POST_BLOGS_FAILURE = 'POST_BLOGS_FAILURE';